id: A3F47FD39
title: f6722
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:13:58.992096
  last_modified_at: 2022-05-27 17:13:58.992104
