id: A3F47FD39
title: fDF10
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:13:59.004229
  last_modified_at: 2022-05-27 17:13:59.004232
